/**
 * Tiny markdown → HTML renderer.
 *
 * Pulse / Research / Glossary bodies are generated by our own Claude
 * pipeline using a constrained markdown subset, so we don't need the
 * full CommonMark / GFM surface. This keeps the bundle small and the
 * sanitization story simple (no library, no XSS surface beyond what
 * we generate ourselves).
 *
 * Supported syntax:
 *   - Headings: # H1 / ## H2 / ### H3 (we only emit h2 + h3 since the
 *     <article> already has its own h1).
 *   - **bold** / *italic* / `inline code`
 *   - [link text](https://example.com)
 *   - Blockquotes: > line
 *   - Unordered lists: - item / * item
 *   - Ordered lists: 1. item
 *   - Horizontal rule: ---
 *   - Paragraphs (blank-line separated)
 *
 * Everything else is rendered as a literal escaped paragraph.
 * The output is intended to be injected via dangerouslySetInnerHTML
 * inside a Tailwind-styled `prose` container.
 */

const ESCAPE: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

function escape(input: string): string {
  return input.replace(/[&<>"']/g, (c) => ESCAPE[c] ?? c);
}

/** Inline markdown — bold/italic/code/link. Run AFTER block parse. */
function inline(text: string): string {
  let out = escape(text);

  // inline code first so it doesn't get mangled
  out = out.replace(/`([^`]+)`/g, (_, code) => {
    return `<code>${code}</code>`;
  });

  // bold
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  out = out.replace(/__([^_]+)__/g, '<strong>$1</strong>');

  // italic
  out = out.replace(/(^|\W)\*([^*\n]+)\*(\W|$)/g, '$1<em>$2</em>$3');
  out = out.replace(/(^|\W)_([^_\n]+)_(\W|$)/g, '$1<em>$2</em>$3');

  // links [label](url) — only http(s) and / paths
  out = out.replace(
    /\[([^\]]+)\]\((https?:\/\/[^)\s]+|\/[^)\s]*)\)/g,
    (_, label: string, url: string) =>
      `<a href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`,
  );

  return out;
}

interface Block {
  kind:
    | 'h1' | 'h2' | 'h3'
    | 'p'
    | 'quote'
    | 'ul' | 'ol'
    | 'hr';
  text?: string;
  items?: string[];
}

function parseBlocks(src: string): Block[] {
  const lines = src.replace(/\r\n/g, '\n').split('\n');
  const blocks: Block[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];

    // Skip blank
    if (line.trim() === '') {
      i += 1;
      continue;
    }

    // Horizontal rule
    if (/^---+$/.test(line.trim())) {
      blocks.push({ kind: 'hr' });
      i += 1;
      continue;
    }

    // Headings
    const h = /^(#{1,3})\s+(.+)$/.exec(line);
    if (h) {
      const level = h[1].length;
      const kind = (`h${level}` as 'h1' | 'h2' | 'h3');
      blocks.push({ kind, text: h[2].trim() });
      i += 1;
      continue;
    }

    // Blockquote (collect contiguous > lines)
    if (line.startsWith('>')) {
      const buf: string[] = [];
      while (i < lines.length && lines[i].startsWith('>')) {
        buf.push(lines[i].replace(/^>\s?/, ''));
        i += 1;
      }
      blocks.push({ kind: 'quote', text: buf.join(' ') });
      continue;
    }

    // Unordered list (- or *)
    if (/^[-*]\s+/.test(line)) {
      const items: string[] = [];
      while (i < lines.length && /^[-*]\s+/.test(lines[i])) {
        items.push(lines[i].replace(/^[-*]\s+/, ''));
        i += 1;
      }
      blocks.push({ kind: 'ul', items });
      continue;
    }

    // Ordered list (1.)
    if (/^\d+\.\s+/.test(line)) {
      const items: string[] = [];
      while (i < lines.length && /^\d+\.\s+/.test(lines[i])) {
        items.push(lines[i].replace(/^\d+\.\s+/, ''));
        i += 1;
      }
      blocks.push({ kind: 'ol', items });
      continue;
    }

    // Paragraph (collect contiguous non-empty, non-special lines)
    const buf: string[] = [];
    while (
      i < lines.length &&
      lines[i].trim() !== '' &&
      !/^(#{1,3}\s|---+$|>|\s*[-*]\s+|\d+\.\s+)/.test(lines[i])
    ) {
      buf.push(lines[i]);
      i += 1;
    }
    if (buf.length > 0) {
      blocks.push({ kind: 'p', text: buf.join(' ') });
    }
  }
  return blocks;
}

/** Render a markdown string to a sanitized HTML string. */
export function renderMarkdown(src: string | null | undefined): string {
  if (!src) return '';
  const blocks = parseBlocks(src);
  return blocks
    .map((b) => {
      switch (b.kind) {
        case 'hr':
          return '<hr />';
        case 'h1':
          return `<h2>${inline(b.text!)}</h2>`; // demote h1 → h2 inside article
        case 'h2':
          return `<h2>${inline(b.text!)}</h2>`;
        case 'h3':
          return `<h3>${inline(b.text!)}</h3>`;
        case 'quote':
          return `<blockquote>${inline(b.text!)}</blockquote>`;
        case 'ul':
          return `<ul>${b.items!.map((it) => `<li>${inline(it)}</li>`).join('')}</ul>`;
        case 'ol':
          return `<ol>${b.items!.map((it) => `<li>${inline(it)}</li>`).join('')}</ol>`;
        case 'p':
          return `<p>${inline(b.text!)}</p>`;
      }
    })
    .join('\n');
}
