-- Migration 009: glossary_entries
--
-- Supabase-backed glossary that supersedes the static glossaryData.ts in code.
-- Generated by PD's glossary-generator module via Claude with country-specific
-- context. Each (country_code, locale, slug) tuple is one entry.
--
-- For "global" entries (country_code = 'global'), the body is country-neutral
-- (e.g., what is the Gini Index, generally). For country-specific entries
-- (country_code = 'TR'), the body is anchored to that country's live data.

CREATE TABLE IF NOT EXISTS glossary_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL,                              -- e.g. 'structural-unemployment'
  country_code text NOT NULL DEFAULT 'global',     -- 'global' | ISO2
  locale text NOT NULL DEFAULT 'en',
  term text NOT NULL,                              -- 'Structural Unemployment'
  short_definition text NOT NULL,                  -- 1-sentence (for tooltips + SERP snippets)
  body_markdown text NOT NULL,                     -- 400-800 word article
  related_indicators text[] NOT NULL DEFAULT '{}', -- indicator ids
  related_meta_indexes text[] NOT NULL DEFAULT '{}', -- economic/social/mental/...
  related_terms text[] NOT NULL DEFAULT '{}',      -- slugs of related glossary entries
  data_snapshot jsonb,                             -- raw values used in the body for audit
  sources jsonb,                                   -- [{name, url}] citations
  generated_by text DEFAULT 'claude-sonnet',
  generated_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_glossary_country_locale_slug
  ON glossary_entries(country_code, locale, slug);

CREATE INDEX IF NOT EXISTS idx_glossary_locale_term
  ON glossary_entries(locale, term);

CREATE INDEX IF NOT EXISTS idx_glossary_country_published
  ON glossary_entries(country_code, published_at DESC);

ALTER TABLE glossary_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read glossary_entries"
  ON glossary_entries FOR SELECT USING (true);

GRANT SELECT ON glossary_entries TO anon, authenticated;

-- View: latest entry per (country, locale, slug) for fast UI reads
CREATE OR REPLACE VIEW v_glossary_latest
WITH (security_invoker = true) AS
SELECT DISTINCT ON (country_code, locale, slug) *
FROM glossary_entries
ORDER BY country_code, locale, slug, generated_at DESC;

GRANT SELECT ON v_glossary_latest TO anon, authenticated;

COMMENT ON TABLE glossary_entries IS 'Claude-generated glossary entries, per (country, locale, slug). Each is an SEO landing page.';
COMMENT ON COLUMN glossary_entries.country_code IS '"global" for country-neutral, ISO2 for country-anchored.';
