-- Migration 010: research_articles
--
-- Long-form pillar content (1500-2500 words) — country + locale specific.
-- Generated by PD's research-generator monthly per country. Each is an SEO
-- pillar piece that synthesizes data across all 5 meta-indexes for a single
-- thematic question (e.g. "AI Job Displacement Outlook for Germany").
--
-- Separate from commentary (Pulse = weekly current-state summary) and
-- glossary_entries (definitional reference). Research articles are
-- analytical deep-dives.

CREATE TABLE IF NOT EXISTS research_articles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL,                            -- 'ai-displacement-outlook-de-2026'
  country_code text NOT NULL DEFAULT 'global',   -- 'global' | ISO2
  locale text NOT NULL DEFAULT 'en',
  topic_id text NOT NULL,                        -- one of TOPICS in PD config
  title text NOT NULL,
  subtitle text,
  excerpt text NOT NULL,                         -- 1-2 sentence hook, SERP snippet
  body_markdown text NOT NULL,                   -- 1500-2500 words
  related_indicators text[] NOT NULL DEFAULT '{}',
  related_meta_indexes text[] NOT NULL DEFAULT '{}',
  related_terms text[] NOT NULL DEFAULT '{}',
  data_snapshot jsonb,                           -- raw values used as evidence
  sources jsonb,                                 -- [{name, url}, ...]
  word_count int,
  reading_time_min int,
  generated_by text DEFAULT 'claude-sonnet',
  generated_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_research_country_locale_slug
  ON research_articles(country_code, locale, slug);

CREATE INDEX IF NOT EXISTS idx_research_country_locale_topic
  ON research_articles(country_code, locale, topic_id);

CREATE INDEX IF NOT EXISTS idx_research_country_published
  ON research_articles(country_code, published_at DESC);

ALTER TABLE research_articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read research_articles"
  ON research_articles FOR SELECT USING (true);

GRANT SELECT ON research_articles TO anon, authenticated;

CREATE OR REPLACE VIEW v_research_latest_per_topic
WITH (security_invoker = true) AS
SELECT DISTINCT ON (country_code, locale, topic_id) *
FROM research_articles
ORDER BY country_code, locale, topic_id, generated_at DESC;

GRANT SELECT ON v_research_latest_per_topic TO anon, authenticated;

COMMENT ON TABLE research_articles IS 'Long-form analytical pieces. Generated monthly per (country, locale, topic).';
